### ISSUE TITLE
End date should be after start date

### ISSUE THREAD

**Issue by pedronim** [vaadin-component-factory/vcf-date-range-picker-flow#11]
To reproduce:

1. Open the date range picker with no selection and select a start date.
2. Select an end date that is before the start date.

IS: The date range picker closes with an invalid date range where the end date is before the start date.

<img width="232" alt="Screenshot 2021-05-20 at 12 57 11" src="https://user-images.githubusercontent.com/4959788/118967682-4e3a1280-b96b-11eb-84cd-08a6b9f39906.png">

SHOULD: Since we are expecting to select an end date and it is before the start date, the selected date becomes the new start date. Date range picker stays open until there is a valid date range.

Since I saw in your version how the selection of the date range in the calendar is working and it got me confused, I discussed the algorithm with our team once more. I think the following changes make it easier to understand for a user.

There are basically three rules:

- You always start with the selection of the start date when you open the calendar.
- You always make at least two clicks before the calendar closes automatically (sometimes more).
- The calendar only closes automatically when the selection is a valid date range (start date before or on end date).

To make the expected behavior of the date range picker concerning date selection in the calendar clearer, here are some scenarios (all starting from empty selection):

Scenario A:
1. Open the calendar and select a start date 2021/05/01 and end date 2021/05/05. Calendar closes on second click.
2. Open the calendar again. Select 2021/04/25 (the selection is now 2021/04/25 until 2021/05/05. Calendar stays open. 
3. To confirm the selection you need to either select 2021/05/05 or close the calendar by clicking outside of it. Calendar closes with 2021/04/25 - 2021/05/05.

Scenario B:
1. Open the calendar and select a start date 2021/05/01 and end date 2021/04/25. Calendar stays open. Start date is now 2021/04/25. Select 2021/04/21 - calendar stays open and this is the new start date). Select 2021/05/01. Calendar closes with 2021/04/21 - 2021/05/01.

Scenario C:
1. Open the calendar and select a start date 2021/05/01. Click outside of the calendar and it closes. The textfield shows 2021/05/01 - .
2. Open the calendar. Select 2021/05/05. This is the new start date and the calendar stays open. Select a valid end date to finish the selection.

**Comment by mlopezFC** [comment]
Closing because this issue should be solved in the latest release.
