### ISSUE TITLE
Problems trying to clear component value

### ISSUE THREAD

**Issue by paodb** [vaadin-component-factory/vcf-date-range-picker-flow#24]
Calling setValue(null) or clear() methods to clear the component value does nothing, presentation value remains being displayed in the component. Using clearButton works okay.

**Comment by ssindelar** [comment]
When getValue() is called after clear(), it returns a DateRange Object with startDate and endDate null.

**Comment by ssindelar** [comment]
I found a work around. I overrode the clear() method and set a random ID in the constructor.
```
	@Override
	public void clear() {
		super.clear();
		getId().ifPresent(id -> UI.getCurrent()
				.getPage()
				.executeJs("customElements.whenDefined('vcf-date-range-picker').then(function() {"
						+ "const dateRangePicker = document.getElementById('" + id + "');"
						+ "dateRangePicker.value='null;null';" + "});"));
	}
```
