### ISSUE TITLE
Problem with design and dash

### ISSUE THREAD

**Issue by mlopezFC** [vaadin-component-factory/vcf-date-range-picker-flow#30]
Taken from this [stackoverflow post](https://stackoverflow.com/q/69750067/2593728):

> There are two problems that I have using the EnhancedDateRangePicker in Vaadin 14(source: https://vaadin.com/directory/component/date-range-picker):
> The design is broken when I add the component somewhere in a layout but that happens only when I add a label. If I don't the design is as expected to be. Here is a screenshot to see what exactly happens - enter image description here
> The other problem is that the dash is not visible clearly in this color(light gray I think). Is there a way to change the color of the dash?

![image](https://user-images.githubusercontent.com/28312758/139847840-7d0ea561-fa78-46ae-a095-cd0e69e3c158.png)

**Comment by mlopezFC** [comment]
I tried to reproduce this issue with the info provided in the post, and I couldn't:

```
@Route
@PWA(name = "My Application", shortName = "My Application")
public class MainView extends VerticalLayout {

    public MainView() {
        EnhancedDateRangePicker enhancedDateRangePicker =
                new EnhancedDateRangePicker("Valid from - Valid to");
        HorizontalLayout mainLayout = new HorizontalLayout();
        VerticalLayout verticalLayout = new VerticalLayout();
        verticalLayout.add(enhancedDateRangePicker);
        mainLayout.add(verticalLayout);
        add(mainLayout);
    }
}
```

![image](https://user-images.githubusercontent.com/28312758/139849795-153b3a46-6a9b-4844-b912-c8c7a254ea7b.png)

**Comment by Dilyan-Galabov** [comment]
@mlopezFC mlopezFC The problem is solved. It's not the problem with the component, it is actually the Theme which we are using in our projects and the component just overrides the theme styles and that brokes the component. When I put it on a blank page there is no problem. Thanks, you all very much @mlopezFC for the effort :).

**Comment by mlopezFC** [comment]
Thanks for reporting that this not related to the component.
Regards!
