### ISSUE TITLE
Doesn't work with Vaadin 23.1

### ISSUE THREAD

**Issue by ssi-ips** [vaadin-component-factory/vcf-date-range-picker-flow#38]
EnhancedDateRangePicker (version 3.0.1) is not working with Vaadin 23.1 due to changes in GeneratedVaadinDatePicker. GeneratedVaadinDatePicker doesn't have a setClearButtonVisible any more, because the HasClearButton interface which is implemented by DatePicker.

As a workaround it is possible to subclass EnhancedDateRangePicker, implement the HasClearButton and add the following function to call the correct function.

	@Override
	public void setClearButtonVisible(boolean clearButtonVisible) {
		HasClearButton.super.setClearButtonVisible(clearButtonVisible);
	}

**Comment by simasch** [comment]
Have you tired with version 3.0.0 or 3.0.1?

**Comment by ssi-ips** [comment]
Yes I have tried both.

**Comment by simasch** [comment]
What's the state of this issue?

**Comment by ssi-ips** [comment]
Not fixed with 3.0.2
