### ISSUE TITLE
Vaadin 24 - Component breaks as GeneratedVaadinDatePicker cannot be resolved

### ISSUE THREAD

**Issue by paodb** [vaadin-component-factory/vcf-date-range-picker-flow#43]
Refactor is needed as EnhancedDateRangePicker class depends on GeneratedVaadinDatePicker that [was removed on Vaadin 24](https://github.com/vaadin/flow-components/commit/011cdd6eaab28ac8b97b6e4e247b32e1a575a645).

**Comment by supernicky22** [comment]
Any news on this? Blocking my spring boot 3 update at the moment.

**Comment by zhpetkov** [comment]
I have the same issue that comes from '_overlayContent' in Vaadin 24! 
The issue is: 
"Cannot read properties of undefined (reading 'querySelector')
    at get _overlayContent [as _overlayContent]". It has changed in a new version of Vaadin Date Picker and get _overlayContent() is removed.

**Comment by kristof-taveirne** [comment]
Any news on this? It's blocking my upgrade to Vaadin 24 and Spring Boot 3

**Comment by rabarberwaehe** [comment]
Any news on this? we really need it, otherwise we're blocked on upgrading to Vaadin 24

**Comment by paodb** [comment]
This was resolved in version [5.0.0](https://github.com/vaadin-component-factory/vcf-date-range-picker-flow/releases/tag/5.0.0). Latest release with Vaadin 24 support is [5.0.1](https://github.com/vaadin-component-factory/vcf-date-range-picker-flow/releases/tag/5.0.1).
